### ISSUE TITLE
failed install

### ISSUE THREAD

**Issue by bioSandMan** [dstreett/ATtack#1]
attempted build on Ubuntu 16.04
$make
g++ source/main.cpp source/fileHelper.cpp source/readInfo.cpp source/argCollector.cpp source/fileWriter.cpp source/binarySearch.cpp -O3 -o attack
g++: error: source/binarySearch.cpp: No such file or directory
Makefile:10: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by dstreett** [comment]
I think you are on master. Please, pull down the branch develop (then branch that) and try building then. All testing should be on the code in develop.

I'm going to close this, but if develop isn't working, re-open this.
